---
title: "Why is Good Friday Good?"
author: Lawrence Wu
date: '2026-04-03'
categories: [personal, faith, christianity]
---

Today is Good Friday. Growing up I never asked the question why is Good Friday good. Why would a person who wasn't evil dying on the cross be something good? I hope to briefly explain why Good Friday is such an important Christian holiday.

In Chinese, Good Friday is 耶穌受難日 (Yēsū shòunàn rì), literally "The Day of Jesus' Suffering" and Easter is 復活節 (Fùhuó jié), literally "Resurrection Holiday". I appreciate how the names of the holidays in Mandarin capture the essence of the two days: Jesus’ suffering and Resurrection.

Jesus suffered through his death on the cross and He resurrected. Two realities that Christians around the world commemorated this weekend. Both are core doctrines of Christianity. But why would we care so much about a person dying on a cross? And why should we possibly believe someone resurrected? tl;dr - it is through faith in Jesus' death and resurrection that our sins are forgiven and eternal life / salvation is given.

I didn't consider these things until college. I'm still thankful to God for those seniors who lived in my dorm who shared the gospel with me. I learned the cross was significant because it was through Jesus' death on the cross that man's sins were atoned for. Sin is breaking God's law. Everyone has in some shape or form broken God's law. Deep down we know it. As a non-Christian, I knew it. I became more painfully aware of my sinfulness as I read the Bible and learned about sins of greed, selfishness, lust and anger. As I became more aware of the sin problem, I desperately sought a solution. That's when the gospel finally became "good news", Good Friday became good and I saw Christ's sacrifice as not only significant but personally relevant for me.

Galatians 3:13 summarizes this well:

> Christ redeemed us from the curse of the law by becoming a curse for us

The resurrection is very significant because without it, Jesus would just be someone who made these extraordinary claims (that he could forgive sins and that He was God) and his body would still be in the grave. The resurrection is so significant that if it isn't true, the Bible actually says preaching and our faith is futile and a waste. Any person could have made the same claims Jesus made (though not everyone could have performed the miracles Jesus did). Jesus' resurrection validates what he taught, proves he was in fact God and that he had power over death.

As a non-Christian, I remember asking my friends who were Christian and other Christians I met, "Wait, so you actually believe someone came back from the dead? How is that possible? What evidence is there?" During that time, someone shared this argument from Gary Habermas called the [Minimal Facts Argument](https://ses.edu/minimal-facts-on-the-resurrection-that-even-skeptics-accept) that helped me quite a bit. He identifies 6 historical facts where each of them is confirmed by strong and independent sources, some even critical scholars. The facts were:

1. Jesus died by crucifixion
2. His followers soon afterward had real experiences that they thought were actual appearances of the risen Jesus
3. The disciples lives were transformed as a result, even to the point of being willing to die specifically for their faith in the resurrection message
4. These things were taught very early, soon after the crucifixion
5. James, Jesus’ unbelieving brother, became a Christian due to his own experience that he thought was the resurrected Christ
6. The Christian persecutor Paul (formerly Saul of Tarsus) also became a believer after a similar experience

Once I believed these 6 things to be historically true, it came down to identifying what reality best explains these facts. Some people say Jesus fainted (swoon theory) but this contradicts the first fact. Some people say Jesus had a twin (twin theory) but there wasn't much evidence for this. Some people say the disciples stole the body but it's doubtful the disciples would be willing to be killed for a lie. The resurrection was the only thing that explained all of the minimal facts.

If you’ve never considered these things, I hope you will at least spend some time trying to answer those questions of why did Jesus suffer? And did Jesus really resurrect? And if these things really did happen, what are the implications on my life? I’m happy to have a conversation if you have any questions too.

> The essence of sin is man substituting himself for God, while the essence of salvation is God substituting himself against God and puts himself where only God deserves to be; God sacrifices himself for man and puts himself where only man deserves to be. (John Stott)

> If Jesus rose from the dead, then you have to accept all that he said; if he didn't rise from the dead, then why worry about any of what he said? The issue on which everything hangs is not whether or not you like his teaching, but whether or not he rose from the dead. (Tim Keller)

Every year I try to read through the [Bible passages that correspond to Jesus' last week he walked on the earth](https://www.esv.org/resources/esv-global-study-bible/chart-40-04/). Today I was thinking about Matthew 27:46:

> And about the ninth hour Jesus cried out with a loud voice, saying, “Eli, Eli, lema sabachthani?” that is, “My God, my God, why have you forsaken me?”

Jesus is quoting David's words in Psalm 22:

> My God, my God, why have You forsaken me?\
> Far from my salvation are the words of my groaning.\
> O my God, I call by day, but You do not answer;\
> And by night, but I have no rest.\
> Yet You are holy,\
> Enthroned upon the praises of Israel.

Jesus is quoting Psalm 22:1 while hanging on the cross. David says this because he feels this intense sense of personal abandonment. Jesus feels this too but in a much greater way. Jesus not not only went through intense, unimaginable physical pain but arguably more intense, also unimaginable spiritual pain by being abandoned by the Father.

As a Christian, I will never have to go through what Christ went through because He went to the cross, experiencing the divine judgment I as a sinner deserve and should have experienced. Praise God. The Bible reassures me when it says nothing will be able to separate me from the love of God, which is in Christ Jesus our Lord (Romans 8). How did Jesus show that love? On Good Friday.

> But God demonstrates his own love for us in that while we were still sinners, Christ died for us. (Romans 5:8)
